#pragma once
#include <cctype>
#include <string>
namespace algaguard::host_test {
enum class DevelopmentIdentityState { UNPROVISIONED, DEV_KEY_GENERATING, DEV_CSR_READY, DEV_CERT_PENDING, DEV_IDENTITY_ACTIVE, DEV_IDENTITY_EXPIRED, DEV_IDENTITY_CORRUPT, DEV_IDENTITY_RESET_REQUIRED };
struct IdentityStatusViewModel { std::string primaryText, secondaryText, warningText, diagnosticsText, severityToken, securityProfile{"DEV_SOFTWARE_KEY"}; DevelopmentIdentityState state{}; bool warningPersistent{}; };
inline std::string redactSecretLike(const std::string& value) { std::string normalized; for (unsigned char c : value) if (std::isalnum(c)) normalized += static_cast<char>(std::tolower(c)); for (const auto& blocked : {"sessiontoken","bootstraptoken","bearertoken","accesstoken","refreshtoken","clientsecret","privatekey","keyblob","wifipassword","password","csrbody","certificatebody","cachain"}) if (normalized == blocked) return "[REDACTED]"; return value; }
inline std::string truncateSafe(const std::string& value, std::size_t limit) { if(value.size()<=limit)return value; if(limit<4)return value.substr(0,limit); return value.substr(0,limit-3)+"..."; }
inline IdentityStatusViewModel identityStatusView(DevelopmentIdentityState state, unsigned generation=0, const std::string& suffix={}, const std::string& reason={}) { IdentityStatusViewModel v;v.state=state;v.severityToken="INFO"; switch(state){case DevelopmentIdentityState::UNPROVISIONED:v.primaryText="DEV IDENTITY";v.secondaryText="UNPROVISIONED";break;case DevelopmentIdentityState::DEV_KEY_GENERATING:v.primaryText="DEV KEY";v.secondaryText="GENERATING";break;case DevelopmentIdentityState::DEV_CSR_READY:v.primaryText="DEV CSR";v.secondaryText="READY";break;case DevelopmentIdentityState::DEV_CERT_PENDING:v.primaryText="DEV CERT";v.secondaryText="PENDING";break;case DevelopmentIdentityState::DEV_IDENTITY_ACTIVE:v.primaryText="DEV IDENTITY";v.secondaryText="ACTIVE";v.warningText="INSECURE DEV KEY";v.warningPersistent=true;v.severityToken="WARNING";break;case DevelopmentIdentityState::DEV_IDENTITY_EXPIRED:v.primaryText="DEV IDENTITY";v.secondaryText="EXPIRED";break;case DevelopmentIdentityState::DEV_IDENTITY_CORRUPT:v.primaryText="DEV IDENTITY";v.secondaryText="CORRUPT";break;case DevelopmentIdentityState::DEV_IDENTITY_RESET_REQUIRED:v.primaryText="DEV IDENTITY";v.secondaryText="RESET REQUIRED";break;} v.diagnosticsText="DEV_SOFTWARE_KEY state="+v.secondaryText+" gen="+std::to_string(generation)+" fp="+truncateSafe(suffix,12)+" reason="+truncateSafe(redactSecretLike(reason),16);return v;}
}
