#pragma once

// Dependency-free security-profile boundary shared by firmware and host probes.
#if defined(ALGAGUARD_SECURITY_PROFILE_DEV_SOFTWARE_KEY) && \
    (!defined(ALGAGUARD_ALLOW_INSECURE_KEY_STORAGE) || ALGAGUARD_ALLOW_INSECURE_KEY_STORAGE != 1)
#error "ALGAGUARD_GUARD_DEV_SOFTWARE_KEY_REQUIRES_INSECURE_STORAGE_OPT_IN"
#endif

#if defined(ALGAGUARD_PRODUCTION_BUILD) && defined(ALGAGUARD_SECURITY_PROFILE_DEV_SOFTWARE_KEY)
#error "ALGAGUARD_GUARD_PRODUCTION_FORBIDS_DEV_SOFTWARE_KEY"
#endif

#if defined(ALGAGUARD_PRODUCTION_BUILD) && defined(ALGAGUARD_DEV_IDENTITY_SELF_TEST)
#error "ALGAGUARD_GUARD_PRODUCTION_FORBIDS_DEV_IDENTITY_SELF_TEST"
#endif

#if defined(ALGAGUARD_ENABLE_DS_PROVIDER) && defined(ALGAGUARD_SECURITY_PROFILE_DEV_SOFTWARE_KEY)
#error "ALGAGUARD_GUARD_DS_AND_DEV_SOFTWARE_KEY_MUTUALLY_EXCLUSIVE"
#endif
