#pragma once

// Dependency-free security-profile boundary shared by firmware and host probes.
#if defined(ALGAGUARD_SECURITY_PROFILE_DEV_SOFTWARE_KEY) && \
    (!defined(ALGAGUARD_ALLOW_INSECURE_KEY_STORAGE) || ALGAGUARD_ALLOW_INSECURE_KEY_STORAGE != 1)
#error "ALGAGUARD_GUARD_DEV_SOFTWARE_KEY_REQUIRES_INSECURE_STORAGE_OPT_IN"
#endif

#if defined(ALGAGUARD_PRODUCTION_BUILD) && defined(ALGAGUARD_SECURITY_PROFILE_DEV_SOFTWARE_KEY)
#error "ALGAGUARD_GUARD_PRODUCTION_FORBIDS_DEV_SOFTWARE_KEY"
#endif

#if defined(ALGAGUARD_PRODUCTION_BUILD) && defined(ALGAGUARD_DEV_IDENTITY_SELF_TEST)
#error "ALGAGUARD_GUARD_PRODUCTION_FORBIDS_DEV_IDENTITY_SELF_TEST"
#endif

#if defined(ALGAGUARD_ENABLE_DS_PROVIDER) && defined(ALGAGUARD_SECURITY_PROFILE_DEV_SOFTWARE_KEY)
#error "ALGAGUARD_GUARD_DS_AND_DEV_SOFTWARE_KEY_MUTUALLY_EXCLUSIVE"
#endif

#if defined(ALGAGUARD_PHYSICAL_TEST_MODE) && \
    (!defined(ALGAGUARD_DEVELOPMENT_BUILD) || ALGAGUARD_DEVELOPMENT_BUILD != 1 || \
     !defined(ALGAGUARD_DEVELOPMENT_PHYSICAL_TEST_OPT_IN) || \
     ALGAGUARD_DEVELOPMENT_PHYSICAL_TEST_OPT_IN != 1)
#error "ALGAGUARD_GUARD_PHYSICAL_TEST_REQUIRES_DEVELOPMENT_OPT_IN"
#endif

#if defined(ALGAGUARD_ENABLE_LOCAL_MOCK_SENSORS) && \
    (!defined(ALGAGUARD_LOCAL_DEMO_MODE) || ALGAGUARD_LOCAL_DEMO_MODE != 1 || \
     !defined(ALGAGUARD_DEVELOPMENT_BUILD) || ALGAGUARD_DEVELOPMENT_BUILD != 1)
#error "ALGAGUARD_GUARD_LOCAL_MOCK_SENSORS_REQUIRE_DEVELOPMENT_DEMO"
#endif

#if defined(ALGAGUARD_ENABLE_QR_ONBOARDING) && \
    (!defined(ALGAGUARD_ENV_DEVELOPMENT) || \
     !defined(ALGAGUARD_PHYSICAL_TEST_MODE) || \
     !defined(ALGAGUARD_DEVELOPMENT_PHYSICAL_TEST_OPT_IN))
#error "ALGAGUARD_GUARD_QR_ONBOARDING_REQUIRES_DEVELOPMENT_PHYSICAL_PROFILE"
#endif

#if defined(ALGAGUARD_ENABLE_QR_ONBOARDING) && \
    (!defined(ALGAGUARD_PRODUCTION_ELIGIBLE) || ALGAGUARD_PRODUCTION_ELIGIBLE != 0)
#error "ALGAGUARD_GUARD_PRODUCTION_FORBIDS_QR_ONBOARDING"
#endif

#if defined(ALGAGUARD_ENABLE_LOCAL_MOCK_SENSORS) && \
    (defined(ALGAGUARD_PRODUCTION_BUILD) || defined(ALGAGUARD_RELEASE_BUILD) || \
     defined(ALGAGUARD_ENABLE_DS_PROVIDER))
#error "ALGAGUARD_GUARD_PRODUCTION_FORBIDS_LOCAL_MOCK_SENSORS"
#endif

#if defined(ALGAGUARD_PHYSICAL_TEST_MODE) && \
    (defined(ALGAGUARD_PRODUCTION_BUILD) || defined(ALGAGUARD_RELEASE_BUILD))
#error "ALGAGUARD_GUARD_PRODUCTION_FORBIDS_PHYSICAL_TEST"
#endif

#if defined(ALGAGUARD_PHYSICAL_TEST_MODE) && defined(ALGAGUARD_ENABLE_DS_PROVIDER)
#error "ALGAGUARD_GUARD_PHYSICAL_TEST_FORBIDS_DS_PROVIDER"
#endif

#if defined(ALGAGUARD_PHYSICAL_TEST_MODE) && \
    (!defined(ALGAGUARD_WIFI_CREDENTIAL_PERSISTENCE_DISABLED) || \
     ALGAGUARD_WIFI_CREDENTIAL_PERSISTENCE_DISABLED != 1)
#error "ALGAGUARD_GUARD_PHYSICAL_TEST_REQUIRES_VOLATILE_WIFI"
#endif
