"""Generate the SSD1306 page-order AlgaGuard boot splash from the approved logo."""

from pathlib import Path

from PIL import Image, ImageOps


SOURCE = Path(r"D:\algaguard-project\brand\algaguard-logo.png")
OUTPUT = Path(__file__).resolve().parents[1] / "include" / "algaguard" / "brand_splash.hpp"
WIDTH, HEIGHT = 128, 64


def main() -> None:
    if not SOURCE.is_file():
        raise SystemExit(f"Approved logo is missing: {SOURCE}")
    with Image.open(SOURCE) as image:
        grayscale = image.convert("L")
        mask = grayscale.point(lambda value: 255 if value < 238 else 0)
        bbox = mask.getbbox()
        if bbox is None:
            raise SystemExit("Approved logo did not contain visible shield pixels")
        logo = grayscale.crop(bbox)
        logo.thumbnail((82, 56), Image.Resampling.LANCZOS)
        canvas = Image.new("L", (WIDTH, HEIGHT), 255)
        canvas.paste(logo, ((WIDTH - logo.width) // 2, (HEIGHT - logo.height) // 2))
        bits = ImageOps.autocontrast(canvas).point(lambda value: 1 if value < 180 else 0)

    packed: list[int] = []
    for page in range(HEIGHT // 8):
        for x in range(WIDTH):
            value = 0
            for bit in range(8):
                if bits.getpixel((x, page * 8 + bit)):
                    value |= 1 << bit
            packed.append(value)

    lines = [
        "// Generated by tools/generate_oled_splash.py; do not edit manually.",
        "#pragma once",
        "#include <array>",
        "#include <cstdint>",
        "namespace algaguard::brand {",
        "constexpr std::array<std::uint8_t, 1024> kOledBootSplash = {",
    ]
    for start in range(0, len(packed), 16):
        chunk = ", ".join(f"0x{value:02X}" for value in packed[start : start + 16])
        lines.append(f"  {chunk},")
    lines.extend(["};", "}  // namespace algaguard::brand", ""])
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
